
CREATE TABLE IF NOT EXISTS "trick"
("id"   SERIAL ,
"name" VARCHAR(255) NOT NULL UNIQUE,
 "complexity" INTEGER NOT NULL, "
description"
 VARCHAR(255) NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "user" (
"id"   SERIAL ,
"nickname" VARCHAR(255) NOT NULL UNIQUE,
"fullName" VARCHAR(255) NOT NULL,
 "email" VARCHAR(255) NOT NULL UNIQUE,
 "description" VARCHAR(255) NOT NULL, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "user_trick" (
"id"   SERIAL ,
"is_done" BOOLEAN NOT NULL,
 "UserId" INTEGER REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
 "TrickId" INTEGER REFERENCES "trick" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE ("UserId", "TrickId"), PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "thread" (
"id"   SERIAL ,
 "user_id" INTEGER NOT NULL,
  "trick_id" INTEGER NOT NULL,
   "UserTrickId" INTEGER
   REFERENCES "user_trick" ("id") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "thread_participant" (
"id"   SERIAL ,
 "in_thread" BOOLEAN NOT NULL,
 "UserId" INTEGER REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
 "ThreadId" INTEGER REFERENCES "thread" ("id") ON DELETE CASCADE ON UPDATE CASCADE,
  UNIQUE ("UserId", "ThreadId"),
 PRIMARY KEY ("id"));

CREATE TABLE IF NOT EXISTS "message" (
"id"   SERIAL ,
"body" VARCHAR(255) NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL,
"updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL,
 "UserId" INTEGER REFERENCES "user" ("id") ON DELETE SET NULL ON UPDATE CASCADE,
"ThreadId" INTEGER REFERENCES
 "thread" ("id") ON DELETE SET NULL ON UPDATE CASCADE, PRIMARY KEY ("id"));
